import { currentZoneId, isCampZone, CAMP_REGEN_MULTIPLIER, getPlayerMaxHp, getPlayerAttack, getPlayerDefense, formatNumber, mainline, ENEMY } from '../game-state';
import { setText, setNumber, setHtml, pick } from '../dom';
import { renderCodexTags, zoneRefMarkup, enemyRefMarkup } from '../codex-ref';
import type { GameState, PageDefinition } from '../types';

/* 资源条存的是原始数值，显示交给 setNumber：大了自动缩写，悬停显示完整数字。 */
const RESOURCES = [
  { label: '金币 / GOLD', get: (state: GameState) => state.gold },
  { label: '废料 / SCRAP', get: (state: GameState) => state.scrap },
  { label: '精华 / ESSENCE', get: (state: GameState) => state.essence }
];
/* 描述拆成两段：copyMain 只在区域 / 敌人 / 状态变化时重绘（里面有图鉴引用，重绘会打断悬停），
   copyHp 是每 500ms 都在变的生命值，单独 setText，避免整段 innerHTML 反复重建。 */
/* 攻击 / 防御排在前面：它们才是「远征队现在什么水平」的答案 —— 换了装备不用切到冒险页就能看到变化。
   两格都是 setNumber（大数自动缩写 + 悬停出精确值），.hero-stats 按子项数量等分，加项不用改 CSS。 */
const HERO = `<div class="panel-heading"><div><span class="panel-kicker">EXPEDITION STATUS</span><h3 data-ref="zone"></h3></div><span class="zone-status" data-ref="status"></span></div><p class="hero-copy"><span data-ref="copyMain"></span><span data-ref="copyHp"></span></p><div class="hero-stats"><div class="mini-stat"><span>攻击</span><b data-ref="attack"></b></div><div class="mini-stat"><span>防御</span><b data-ref="defense"></b></div><div class="mini-stat"><span>已完成战斗</span><b data-ref="wins"></b></div><div class="mini-stat"><span>当前敌人</span><b data-ref="enemy"></b></div></div><button class="primary-button" data-page="adventure" type="button" data-ref="cta"></button>`;
/** 主线节点的达成条件：达成的点亮，未达成的显示当前进度文案（与远征档案里同一套 .requirement 样式）。
    text() 返回的引用 HTML 直接可用；再过一遍 renderCodexTags 是兜底——万一某条文案写成 [[kind:id]] 标记，也不会把标记原样显示出来。 */
const questRequirements = (state: GameState, index: number) => mainline[index].requirements.map(entry => { const done = entry.done(state); return `<div class="requirement ${done ? 'done' : ''}"><span class="status-dot ${done ? '' : 'pending'}"></span><span>${renderCodexTags(entry.text(state))}</span></div>`; }).join('');
/* 日志正文里的 [[类型:下标]] 标记渲染成图鉴引用（icon + 名称 + 类型色 + 可点开图鉴）。 */
const logMarkup = (state: GameState) => state.log.length ? state.log.slice(0, 6).map(entry => `<div class="log-entry log-${entry.type || 'system'}"><span class="log-time">${entry.time}</span><span>${renderCodexTags(entry.message)}</span></div>`).join('') : '<div class="log-entry"><span class="log-time">现在</span><span>战斗记录将在远征队出发后出现。</span></div>';
const page: PageDefinition<any> = { id: 'home', template: './pages/home.html', mount(root) { const resources = root.querySelector<HTMLElement>('#home-resources')!; resources.innerHTML = RESOURCES.map(item => `<div class="resource"><span class="resource-label">${item.label}</span><strong class="resource-value"></strong></div>`).join(''); setHtml(root.querySelector('#home-hero'), HERO); setHtml(root.querySelector('#home-quest'), `<div class="panel-heading"><div><span class="panel-kicker">MAINLINE</span><h3>当前主线</h3></div><span class="muted" data-ref="progress"></span></div><div data-ref="body"></div><button class="secondary-button wide" data-page="inventory" type="button">打开物品栏</button>`); return { values: [...resources.querySelectorAll('.resource-value')], hero: pick(root.querySelector('#home-hero')!, 'zone', 'status', 'copyMain', 'copyHp', 'attack', 'defense', 'wins', 'enemy', 'cta'), quest: pick(root.querySelector('#home-quest')!, 'progress', 'body'), log: root.querySelector<HTMLElement>('#home-log') }; }, update(state, ctx) { RESOURCES.forEach((item, index) => { setNumber(ctx.values[index], item.get(state)); }); const zoneId = currentZoneId(state); const camp = isCampZone(zoneId); const enemyId = state.adventure.enemyId;
    /* 刷怪冷却期间场上没有敌人（adventure.enemyId 还留着上一只被打掉的怪），
       这时「当前敌人」要显示等待，而不是那只已经死掉的怪 —— 与冒险页的 spawning 判断保持一致。 */
    const spawning = !camp && state.adventure.spawnTimer > 0;
    setHtml(ctx.hero.zone, zoneRefMarkup(zoneId)); setText(ctx.hero.status, camp ? '休整' : spawning ? '搜寻中' : state.adventure.running ? '战斗中' : '待命'); setHtml(ctx.hero.copyMain, camp ? `远征队在${zoneRefMarkup(zoneId)}休整。这里不会遭遇敌人，生命恢复速度是野外的 ${CAMP_REGEN_MULTIPLIER} 倍。` : spawning ? `远征队正在${zoneRefMarkup(zoneId)}搜寻目标，下一场战斗即将开始。` : state.adventure.running ? `远征队正在与${enemyRefMarkup(enemyId)}交战。` : `目标区域：${zoneRefMarkup(zoneId)}。下一场可能遭遇${enemyRefMarkup(enemyId)}或${enemyRefMarkup(ENEMY.brute)}。`); setText(ctx.hero.copyHp, camp || !state.adventure.running ? '' : `\n当前生命值 ${formatNumber(state.adventure.playerHp)} / ${formatNumber(getPlayerMaxHp(state))}。`); setNumber(ctx.hero.attack, getPlayerAttack(state)); setNumber(ctx.hero.defense, getPlayerDefense(state)); setNumber(ctx.hero.wins, state.totalWins); setHtml(ctx.hero.enemy, camp ? '篝火' : spawning ? '等待敌人出现' : enemyRefMarkup(enemyId)); setText(ctx.hero.cta, state.adventure.running ? '查看实时战斗' : '前往冒险页面'); setText(ctx.quest.progress, `${state.mainlineIndex}/${mainline.length}`); setHtml(ctx.quest.body, state.mainlineIndex < mainline.length ? `<article class="quest"><div class="quest-title"><span>${mainline[state.mainlineIndex].title}</span><span>进行中</span></div><p class="quest-desc">${mainline[state.mainlineIndex].description}</p><div class="quest-requirements">${questRequirements(state, state.mainlineIndex)}</div><div class="quest-reward">${mainline[state.mainlineIndex].reward}</div></article>` : '<div class="story-quote">边境调查阶段已经完成。新的区域信号正在等待确认。</div>'); setHtml(ctx.log, logMarkup(state)); } };
export default page;
