import { items, rarities, devStats, devGrantItem, devSetStat, devUnlockSystems, getState, getOwnedCount, fontScales, getFontScale, setFontScale, formatNumber } from '../game-state';
import { setText, setClass, pick } from '../dom';
import type { GameState, PageDefinition } from '../types';

/* ——— 开发者面板 ———
   下面这些只被 `if (__DEV_TOOLS__)` 引用。构建时把开关关掉（DEV_TOOLS=false），
   __DEV_TOOLS__ 会被替换成字面量 false，条件分支被移除，这些函数连同它们依赖的
   devGrantItem / devSetStat / devUnlockSystems / devStats 都会作为死代码从产物里消失。 */

/** 「增加物品」悬浮窗里的发放档位，值即按钮上的 data-dev-multiplier。 */
const DEV_AMOUNTS = [1, 5, 10, 100];
let devModalEl: HTMLElement | null = null;
let devMultiplier = DEV_AMOUNTS[0];

/* 一个物品一个按钮。装备这类不堆叠的物品，发 5 件就是 5 张卡片（见 pages/inventory.ts）。 */
function devItemButtonsMarkup(): string { return items.map((item, id) => `<button class="dev-item-button rarity-${rarities[item.rarity].className}" type="button" data-dev-grant="${id}"><span class="dev-item-icon">${item.icon}</span><span class="dev-item-name">${item.name}</span><span class="dev-item-owned" data-dev-owned="${id}"></span></button>`).join(''); }
/** 悬浮窗只建一次，之后复用；挂在 body 上，不受设置页重绘影响。 */
function ensureDevModal(): HTMLElement { if (devModalEl) return devModalEl; const modal = document.createElement('div'); modal.className = 'dev-modal-layer'; modal.hidden = true; modal.innerHTML = `<div class="dev-modal"><div class="dev-modal-head"><div><span class="panel-kicker">DEVELOPER</span><h3>增加物品</h3></div><button class="dev-modal-close" type="button" data-dev-close aria-label="关闭">×</button></div><div class="dev-item-grid">${devItemButtonsMarkup()}</div><div class="dev-modal-foot"><span class="dev-multiplier-label">每次发放</span><div class="segmented">${DEV_AMOUNTS.map(amount => `<button class="segment" type="button" data-dev-multiplier="${amount}">×${amount}</button>`).join('')}</div></div></div>`; modal.addEventListener('click', event => { const target = event.target as Element; /* 点关闭按钮、或点在遮罩本身上（不是它的子节点）都关窗。 */ if (target.closest('[data-dev-close]') || target.classList.contains('dev-modal-layer')) { closeDevModal(); return; } const amountButton = target.closest<HTMLElement>('[data-dev-multiplier]'); if (amountButton) { devMultiplier = Number(amountButton.dataset.devMultiplier); syncDevModal(); return; } const grantButton = target.closest<HTMLElement>('[data-dev-grant]'); if (grantButton) { devGrantItem(Number(grantButton.dataset.devGrant), devMultiplier); syncDevModal(); } }); document.addEventListener('keydown', event => { if (event.key === 'Escape') closeDevModal(); }); document.body.appendChild(modal); devModalEl = modal; return modal; }
/** 同步档位高亮与每个物品按钮上的持有数。 */
function syncDevModal(): void { if (!devModalEl) return; devModalEl.querySelectorAll<HTMLElement>('[data-dev-multiplier]').forEach(button => setClass(button, 'active', Number(button.dataset.devMultiplier) === devMultiplier)); const state = getState(); devModalEl.querySelectorAll<HTMLElement>('[data-dev-owned]').forEach(element => setText(element, `×${formatNumber(getOwnedCount(Number(element.dataset.devOwned), state))}`)); }
function openDevModal(): void { const modal = ensureDevModal(); modal.hidden = false; syncDevModal(); }
function closeDevModal(): void { if (devModalEl) devModalEl.hidden = true; }

function devPanelMarkup(): string { const statRows = devStats.map((entry, index) => `<label class="dev-row"><span class="dev-row-name">${entry.name}</span><input class="dev-input" type="number" min="0" data-dev-stat="${index}"></label>`).join(''); return `<section class="dev-panel"><div class="dev-head"><span class="panel-kicker">DEVELOPER</span><h3>开发者功能</h3><p>直接修改存档数据，改动立即写入存档。这个面板只在构建时开启开发者开关的情况下才会出现在产物里。</p></div><div class="dev-group"><h4>增加物品</h4><div class="dev-list"><div class="dev-row"><span class="dev-row-name">发放物品到物品栏</span><span class="dev-row-actions"><button class="dev-button" type="button" data-dev-action="items">打开物品面板</button></span></div></div></div><div class="dev-group"><h4>修改属性</h4><div class="dev-list">${statRows}</div></div><div class="dev-group"><h4>解锁系统</h4><div class="dev-list"><div class="dev-row"><span class="dev-row-name">一键解锁全部系统</span><span class="dev-row-actions"><button class="dev-button" type="button" data-dev-action="unlock">解锁</button></span></div></div></div></section>`; }
function devPanelMount(view: HTMLElement, ctx: any): void { ctx.devInputs = [...view.querySelectorAll<HTMLInputElement>('[data-dev-stat]')]; view.addEventListener('click', event => { const action = (event.target as Element).closest<HTMLElement>('[data-dev-action]'); if (!action) return; if (action.dataset.devAction === 'items') openDevModal(); else if (action.dataset.devAction === 'unlock') devUnlockSystems(); }); view.addEventListener('change', event => { const input = (event.target as Element).closest<HTMLInputElement>('[data-dev-stat]'); if (input) devSetStat(Number(input.dataset.devStat), Number(input.value)); }); }
function devPanelSync(state: GameState, ctx: any): void { /* 正在输入的框不要回写，否则会打断输入。 */ ctx.devInputs.forEach((input: HTMLInputElement) => { const value = String(devStats[Number(input.dataset.devStat)].get(state)); if (document.activeElement !== input && input.value !== value) input.value = value; }); /* 悬浮窗开着时，按钮上的持有数跟着刷新。 */ if (devModalEl && !devModalEl.hidden) syncDevModal(); }

const page: PageDefinition<any> = { id: 'settings', template: './pages/settings.html', mount(root) { const view = root.querySelector<HTMLElement>('#settings-view')!; let devMarkup = ''; if (__DEV_TOOLS__) devMarkup = devPanelMarkup(); view.innerHTML = `<div class="setting-row"><div class="setting-copy"><span class="panel-kicker">FONT SIZE</span><h3>字体大小</h3><span data-ref="current" class="muted"></span></div><div class="segmented" data-ref="group">${fontScales.map((option, id) => `<button class="segment" type="button" data-scale="${id}">${option.label}</button>`).join('')}</div></div><div class="setting-row"><div class="setting-copy"><span class="panel-kicker">DANGER ZONE</span><h3>重置存档</h3><p>清空当前远征进度，从一簇微弱的火星重新开始。</p></div><button class="secondary-button danger" type="button" data-action="reset">重置存档</button></div>${devMarkup}`; const refs = pick(view, 'current', 'group'); refs.group!.addEventListener('click', event => { const button = (event.target as Element).closest<HTMLButtonElement>('[data-scale]'); if (button) setFontScale(Number(button.dataset.scale)); }); const ctx: any = { current: refs.current, buttons: [...refs.group!.querySelectorAll<HTMLButtonElement>('[data-scale]')] }; if (__DEV_TOOLS__) devPanelMount(view, ctx); return ctx; }, update(state: GameState, ctx: any) { ctx.buttons.forEach((button: HTMLButtonElement) => setClass(button, 'active', Number(button.dataset.scale) === state.settings.fontScale)); setText(ctx.current, `当前：${getFontScale(state).label}`); if (__DEV_TOOLS__) devPanelSync(state, ctx); } };
export default page;
