import { getPlayerAttack, upgradeWorkshop, upgradeResearch, upgradeCompanions } from '../game-state';
import { setText, setClass, setHidden, setDisabled, pick } from '../dom';
import type { GameState, PageDefinition } from '../types';
const workshopCost = (state: GameState) => 40 + state.workshop * 35;
const researchCost = (state: GameState) => 2 + state.research * 3;
const companionGold = (state: GameState) => 100 + state.companions * 90;
const companionEssence = (state: GameState) => 4 + state.companions * 3;
const SYSTEMS = [
  { id: 'auto', cta: null, unlocked: () => true, title: () => '自动冒险', desc: () => '基础系统。离线期间继续推进已选择的区域。', cost: () => '永久运行', affordable: () => true },
  { id: 'workshop', cta: '升级', unlocked: (state: GameState) => state.mainlineIndex >= 2, title: (state: GameState) => `工坊 · Lv.${state.workshop}`, desc: (state: GameState) => state.mainlineIndex >= 2 ? '消耗废料强化营地，每级提高生命上限、生命恢复与攻击力。' : '完成第一片区域后解锁。', cost: (state: GameState) => `${workshopCost(state)} 废料`, affordable: (state: GameState) => state.scrap >= workshopCost(state) },
  { id: 'research', cta: '研究', unlocked: (state: GameState) => state.mainlineIndex >= 3, title: (state: GameState) => `研究 · Lv.${state.research}`, desc: (state: GameState) => state.mainlineIndex >= 3 ? '消耗精华研究新技术，每级提高攻击力并缩短攻击间隔。' : '收集 3 个旧电池后解锁。', cost: (state: GameState) => `${researchCost(state)} 精华`, affordable: (state: GameState) => state.essence >= researchCost(state) },
  { id: 'companions', cta: '招募', unlocked: (state: GameState) => state.mainlineIndex >= 4, title: (state: GameState) => `伙伴 · Lv.${state.companions}`, desc: (state: GameState) => state.mainlineIndex >= 4 ? '招募伙伴扩大队伍，每级提高生命上限、生命恢复与攻击力。' : '收集 3 个装甲板后解锁。', cost: (state: GameState) => `${companionGold(state)} 金币 · ${companionEssence(state)} 精华`, affordable: (state: GameState) => state.gold >= companionGold(state) && state.essence >= companionEssence(state) }
];
const ACTIONS: Record<string, () => void> = { workshop: upgradeWorkshop, research: upgradeResearch, companions: upgradeCompanions };
const page: PageDefinition<any> = { id: 'systems', template: './pages/systems.html', mount(root) { const view = root.querySelector<HTMLElement>('#systems-view')!; const cards = SYSTEMS.map(system => `<article class="system-card" data-ref="card"><h3 data-ref="title"></h3><p data-ref="desc"></p><div class="system-action"><span class="cost" data-ref="cost"></span><button class="secondary-button" type="button" data-action="${system.id}" data-ref="cta"></button><span class="zone-status" data-ref="lock"></span></div></article>`).join(''); view.innerHTML = `<div class="systems-summary"><span class="panel-kicker">ATTACK</span><strong data-ref="power"></strong><span>当前攻击力</span></div><div class="system-list">${cards}</div>`; root.onclick = event => { const button = (event.target as Element).closest<HTMLButtonElement>('[data-action]'); if (!button || button.disabled) return; ACTIONS[button.dataset.action || '']?.(); }; return { power: view.querySelector('[data-ref="power"]'), items: [...view.querySelectorAll('.system-card')].map(card => ({ card, ...pick(card, 'title', 'desc', 'cost', 'cta', 'lock') })) }; }, update(state: GameState, ctx: any) { setText(ctx.power, getPlayerAttack(state)); SYSTEMS.forEach((system, index) => { const refs = ctx.items[index]; if (!refs) return; const unlocked = system.unlocked(state); const showCta = unlocked && !!system.cta; setClass(refs.card, 'locked', !unlocked); setText(refs.title, system.title(state)); setText(refs.desc, system.desc(state)); setHidden(refs.cost, !unlocked); setHidden(refs.cta, !showCta); setHidden(refs.lock, showCta); setText(refs.lock, unlocked ? '已解锁' : '未解锁'); if (system.cta) { setText(refs.cta, system.cta); setDisabled(refs.cta as HTMLButtonElement, !system.affordable(state)); } }); } };
export default page;
