import { getState } from './game-state';
import { toFragment, prefersReducedMotion, reportError } from './dom';
import type { PageDefinition } from './types';

const templateCache = new Map<string, Promise<string>>();
let tallestPageHeight = 0;
function loadTemplate(page: PageDefinition): Promise<string> { if (templateCache.has(page.id)) return templateCache.get(page.id)!; const request = fetch(page.template).then(response => { if (!response.ok) throw new Error(`HTTP ${response.status} ${response.statusText} · ${new URL(page.template, document.baseURI).href}`); return response.text(); }).catch(error => { reportError('template', `模板加载失败：${page.template}`, error instanceof Error ? error.message : error); templateCache.delete(page.id); throw error; }); templateCache.set(page.id, request); return request; }

const pageController = {
  pages: new Map<string, PageDefinition>(), currentId: 'home', renderToken: 0, frame: 0, context: null as any,
  register(page: PageDefinition): void { this.pages.set(page.id, page); },
  prefetch(id?: string): void { const page = id ? this.pages.get(id) : undefined; if (!page || templateCache.has(id!)) return; loadTemplate(page).catch(() => {}); },
  prefetchAll(): void { const ids = [...this.pages.keys()]; const run = () => ids.forEach(id => this.prefetch(id)); if ('requestIdleCallback' in window) (window as any).requestIdleCallback(run, { timeout: 2000 }); else setTimeout(run, 200); },
  switchTo(id: string): void { if (!this.pages.has(id)) { reportError('nav', `页面未注册：${id}（已注册：${[...this.pages.keys()].join(', ')}）`); return; } const content = document.querySelector<HTMLElement>('#page-content'); if (!content) { reportError('nav', '找不到 #page-content 容器，无法切换页面'); return; } if (this.currentId === id && content.dataset.page === id) return; this.currentId = id; content.removeAttribute('data-page'); if (!content.childElementCount) content.innerHTML = '<div class="page-loading">正在打开页面…</div>'; if (!templateCache.has(id)) content.classList.add('is-switching'); this.mountPage(id); },
  async mountPage(id: string): Promise<void> { const token = ++this.renderToken; const page = this.pages.get(id)!; let html = ''; try { html = await loadTemplate(page); } catch (error) { if (token !== this.renderToken) return; const content = document.querySelector<HTMLElement>('#page-content'); if (!content) { reportError('render', '找不到 #page-content 容器，无法显示错误占位'); return; } content.classList.remove('is-switching'); content.innerHTML = '<div class="page-error">页面加载失败，请刷新后重试。</div>'; return; } if (token !== this.renderToken) return; const content = document.querySelector<HTMLElement>('#page-content'); if (!content) { reportError('render', '找不到 #page-content 容器，无法挂载页面'); return; } content.onclick = null; content.onchange = null; content.oncontextmenu = null; const apply = () => { try { content.replaceChildren(toFragment(html)); content.dataset.page = id; this.context = page.mount(content) || {}; this.paint(); const height = content.scrollHeight; if (height > tallestPageHeight) { tallestPageHeight = height; content.style.minHeight = `${height}px`; } } catch (error) { reportError('render', `挂载页面失败：${id}`, error instanceof Error ? `${error.message}\n${error.stack}` : error); } }; const reduceMotion = prefersReducedMotion(); const canTransition = typeof (document as any).startViewTransition === 'function' && !reduceMotion; if (canTransition) { try { (document as any).startViewTransition(apply); } catch (error) { reportError('render', 'startViewTransition 调用失败，降级为直接渲染', error instanceof Error ? error.message : error); apply(); } } else { apply(); if (!reduceMotion) content.animate([{ opacity: 0, transform: 'translateY(6px)' }, { opacity: 1, transform: 'none' }], { duration: 180, easing: 'ease-out' }); } content.classList.remove('is-switching'); },
  remeasure(): void { const content = document.querySelector<HTMLElement>('#page-content'); if (!content) return; content.style.minHeight = ''; tallestPageHeight = content.scrollHeight; content.style.minHeight = `${tallestPageHeight}px`; },
  renderCurrent(): void { if (this.frame) return; this.frame = requestAnimationFrame(() => { this.frame = 0; this.paint(); }); },
  paint(): void { const content = document.querySelector<HTMLElement>('#page-content'); const page = this.pages.get(this.currentId); if (!page || !content || content.dataset.page !== this.currentId) return; try { page.update(getState(), this.context); } catch (error) { reportError('render', `页面更新失败：${page.id}`, error instanceof Error ? `${error.message}\n${error.stack}` : error); } }
};
export default pageController;
